name: halem

on:
  schedule:
    # randomize this schedule in order not to test all packages at the same time
    - cron: "5 4 * * FRI"
  push:
    branches:
      - "**"
    tags:
      - "v*"
  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install wheel netCDF4
          pip install -e .[testing]
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest -c pytest-full.ini
      - name: Run coverage
        run: |
          coverage report --fail-under=70
          coverage html
          coverage-badge > htmlcov/coverage.svg
      - name: Publish coverage
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./htmlcov
          destination_dir: coverage
          exclude_assets: .github,.gitignore

  docs:
    needs: test
    runs-on: ubuntu-latest
    # only on tagged releases
    if: startsWith(github.ref, 'refs/tags/v')
    # don't fail the test suite if something goes wrong here
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -e .[docs]
      - name: Create docs
        run: |
          python setup.py docs
      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          destination_dir: docs